# Object Oriented Programming (OOP) in Python 

## OOP versus procedural programming paradigms

A common way to structure a program is to use the __Procedural programming paradigm__:
* define data and function that operates on data
* structures a program like a recipe that it provides a set of steps, in the form of functions and code blocks, that flow sequentially in order to complete a task

An alternative to this approach is provided by the __Object oriented programming paradigm__.

Here we give some definition of what on object is:
* An object is simply a collection of data (variables) and methods (functions) that act on those data.
* Objects are a way to encapsulate variables and functions that operates on them into a single entity.

In a OOP the programmer defines the objects and make them interact. 

## First examples of class definition and usage

Python data structure like for instance a numpy array has the features of an object.

In [1]:
import numpy as np
import random as rand

In [5]:
data = np.array([rand.random() for ind in range(10)])
data

array([0.86711845, 0.69028001, 0.70253927, 0.98537323, 0.65257081,
       0.20787459, 0.01831197, 0.21071877, 0.85844787, 0.05849734])

Since data is np.array we can perform specific (python provided) operation on it

In [7]:
data.mean()

0.5251732310406119

In [8]:
data.argmax()

3

The notion of __class__ allows us to build our own objects with specific data and methods.

Here we discuss a first example

In [20]:
class Person:
    """
    This class describes a person represented by its general features
    like name, age and gender
    """
    
    def __init__(self,name,age,gender):
        """
        To create an instance of the class provide the following parameters
        
        Args:
            name (string) : the name of the person
            age (int) : the age of the person
            gender (string) : the gender of the person
        """
        self.name = name
        self.age = age
        self.gender = gender

    def greet(self):
        """
        I introduce my self
        """
        print("Hello my name is %s, I'm a %s and I'm %s years old"%(self.name,self.gender,self.age))
    
    def ismybirthday(self):
        """
        State that today it is my birthday
        """
        print("Today it's my birthday.!")
        self.age += 1

In [16]:
Person?

Init signature: Person(name, age, gender)
Docstring:     
This class describes a person represented by its general features
like name, age and gender
Init docstring:
To create an instance of the class provide the following parameters

Args:
    name (string) : the name of the person
    age (int) : the age of the person
    gender (string) : the gender of the person
Type:           type
Subclasses:     


In [17]:
marco = Person('marco',44,'male')

In [18]:
marco.greet()

Hello my name is marco, I'm a male and I'm 44 years old


In [19]:
marco.ismybirthday()
marco.age

Hey! Today it's my birthday.!


45

Add some consistency check on the value of the age. 

Introduce the _get_ and _set_ method,

In [56]:
class Person:
    """
    This class describes a person represented by its general features
    like name, age and gender
    """
    
    def __init__(self,name,age,gender):
        """
        To create an instance of the class provide the following parameters
        
        Args:
            name (string) : the name of the person
            age (int) : the age of the person
            gender (string) : the gender of the person
        """
        self.name = name
        self.set_age(age)
        self.gender = gender

    def greet(self):
        """
        I introduce my self
        """
        print("Hello my name is %s, I'm a %s and I'm %s years old"%(self.name,self.gender,self.age))
    
    def ismybirthday(self):
        """
        State that today it is my birthday
        """
        print("Today it's my birthday.!")
        self.age += 1
        
    def set_age(self,age):
        """
        Set the age and check that age is a positive integer
        """
        try: 
            self.age = age
            assert type(age) is int and age > 0 # Test if it true
        except AssertionError :
            raise
        

In [57]:
marco = Person('marco',44,'male')
marco.age

44

In [63]:
type(marco) is Person

True

## Inheritance, parent and child classes 

If we need to add further properties, or to modify some of them, to an existing class we can define a 
child class that inherits from the original one (parent).

For instance use the class person defined above to define class employer

In [159]:
class Employer(Person):
    """
    This class describes an employer defined by adding the level to the 
    attributea of an instance of Person 
    """
    
    def __init__(self,name,age,gender,level):
        Person.__init__(self,name,age,gender)
        self.level = level
    
    def greet(self):
        """
        A more formal greeting
        """
        print("Hello my name is %s and my level is %s"%(self.name,self.level))

In [160]:
Employer?

Init signature: Employer(name, age, gender, level)
Docstring:     
This class describes an employer defined by adding the level to the 
attributea of an instance of Person 
Init docstring:
To create an instance of the class provide the following parameters

Args:
    name (string) : the name of the person
    age (int) : the age of the person
    gender (string) : the gender of the person
Type:           type
Subclasses:     


In [180]:
marco = Employer('marco',44,'male',level=3)

Destructor called, Employer deleted.


In [181]:
marco.greet()

Hello my name is marco and my level is 3


In [182]:
marco.ismybirthday()
marco.age

Today it's my birthday.!


45

In [183]:
type(marco) is Employer

True

Let's define another child class derived from Person

In [207]:
class Director(Person):
    """
    This class describes the Director 
    """
    
    def __init__(self,name,age,gender):
        Person.__init__(self,name,age,gender)
    
    def greet(self):
        """
        Director's greeting
        """
        print("Hello my name is %s and I'm the director"%self.name)
    
    def advance(self,employer):
        """
        Increase the level of the employer
        """
        if type(employer) is not Employer:
            print('Get hired first!')
        elif employer.level == 1:
            print('%s you are already at the top level'%employer.name)
        else:
            employer.level -= 1
            print('%s now your level is %s'%(employer.name,employer.level))
    
    def decrease(self,employer):
        """
        Decrease the level of the employer
        """
        if type(employer) is not Employer:
            print('Get hired first!')
        elif employer.level == 3:
            print('%s you are already at the lowest level'%employer.name)
        else:
            employer.level += 1
            print('%s now your level is %s'%(employer.name,employer.level))

In [217]:
marco = Employer('marco',44,'male',level=3)
claudia = Person('claudia',39,'female')
aldo = Director('aldo',age=50,gender='male')

In [218]:
marco.greet()
claudia.greet()

Hello my name is marco and my level is 3
Hello my name is claudia, I'm a female and I'm 39 years old


In [221]:
aldo.advance(marco)
marco.greet()
aldo.advance(claudia)

marco you are already at the top level
Hello my name is marco and my level is 1
Get hired first!


In [224]:
aldo.decrease(marco)
marco.greet()

marco you are already at the lowest level
Hello my name is marco and my level is 3


## Other (more useful?) examples. Work with QuantumESPRESSO output

In [41]:
# useful to autoreload the module without restarting the kernel
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
import sys
sys.path.append('code')
import PwParser as P

In [43]:
P.PwParser?

Init signature: P.PwParser(file, verbose=True)
Docstring:     
Class to perform the parsing of a QuantumESPRESSO XML file. Makes usage of the
data-file-schema.xml file that is found in the run_dir/prefix.save folder.

The init method initializes the data member of the class.

Args:
    file (str): The name, including the path of the data-file-schema.xml
    verbose (bool) : set the amount of information written on terminal

Attributes:
    natoms : number of atoms in the cell
    natypes : number of atomic species
    atomic_positions : list with the position of each atom
    atomic_species : dictionary with mass and pseudo for each species
    num_electrons : number of electrons
    nkpoints : numer of kpoints
    nbands : number of bands
    nbands_valence : number of occupied bands (for systems with a gap)
    nbands_conduction : number of empty bands (for systems with a gap)
    occupations_kind : type of occupation (fixed or smearing)
    kpoints : list of the kpoints
    occupati

In [61]:
data = P.PwParser('data/gaas_nscf.save/data-file-schema.xml')

Parse file : data/gaas_nscf.save/data-file-schema.xml


We can access to the data members that contain the parsing of the xml file but the class provides also
various specific methods. 

In [62]:
print(data.atomic_species)
print(data.units)
print(data.nbands)
print(data.nbands_full)
print(data.kpoints[0])
print(data.evals[0])

{'Ga': ['1.000000000000000e0', 'Ga_hamlu.fhi.UPF'], 'As': ['1.000000000000000e0', 'As_hamlu.fhi.UPF']}
Hartree atomic units
8
4
[0. 0. 0.]
[-0.29113618  0.18613232  0.18613232  0.18613232  0.20322935  0.32463907
  0.32463907  0.32463907]


The methods contain analysis performed on the data

In [64]:
data.get_evals?

Signature:
data.get_evals(
    set_scissor=None,
    set_gap=None,
    set_direct_gap=None,
    verbose=True,
)
Docstring:
Return the ks energies for each kpoint (in eV). The top of the valence band is used as the
reference energy value. It is possible to shift the energies of the empty bands by setting an arbitrary
value for the gap (direct or indirect) or by adding an explicit scissor.
Implemented only for semiconductors, the energy shift of empty bands does not update their occupation levels.

Args:
    set_scissor (:py:class:`float`) : set the value of the scissor (in eV) that is added to the empty bands.
        If a scissor is provided the set_gap and set_direct_gap parameters are ignored
    set_gap (:py:class:`float`) : set the value of the gap (in eV) of the system. If set_gap is provided
        the set_direct_gap parameter is ignored
    set_direct_gap (:py:class:`float`) : set the value of the direct gap (in eV) of the system.

Return:
    :py:class:`numpy.array`  : an arra

In [68]:
data.get_evals(set_gap=1.42)[0]

Apply a scissor of 0.9547660381861629 eV


array([-1.29871374e+01, -1.19481873e-08, -9.32078947e-09,  0.00000000e+00,
        1.42000000e+00,  4.72372665e+00,  4.72372665e+00,  4.72372665e+00])

In [69]:
data.get_gap()

Direct gap system
Gap : 0.465233961813837 eV


{'gap': 0.465233961813837,
 'direct_gap': 0.465233961813837,
 'position_cbm': 0,
 'positon_vbm': 0}

In [70]:
data.get_transitions?

Signature:
data.get_transitions(
    initial='full',
    final='empty',
    set_scissor=None,
    set_gap=None,
    set_direct_gap=None,
)
Docstring:
Compute the (vertical) transitions energies. For each kpoint compute the transition energies, i.e.
the (positive) energy difference (in eV) between the final and the initial states.

Args:
    initial (string or list) : specifies the bands from which electrons can be extracted. It can be set to `full` or
        `empty` to select the occupied or empty bands, respectively. Otherwise a list of bands can be
        provided
    final  (string or list) : specifies the final bands of the excited electrons. It can be set to `full` or
        `empty` to select the occupied or empty bands, respectively. Otherwise a list of bands can be
        provided
    set_scissor (:py:class:`float`) : set the value of the scissor (in eV) that is added to the empty bands.
        If a scissor is provided the set_gap and set_direct_gap parameters are ignored
 

In [76]:
data.get_transitions(set_gap=1.42,initial=[3],final='empty')

array([[ 1.42      ,  4.72372665,  4.72372665,  4.72372665],
       [ 2.75991809,  5.33235297,  5.33235298,  5.40545784],
       [ 3.044193  ,  6.31035349,  6.31035351,  7.6086607 ],
       [ 3.043431  ,  6.71579805,  6.71579805,  9.64673776],
       [ 3.03619967,  6.77296784,  6.77296784,  9.85236819],
       [ 4.02400266,  4.66973744,  6.41633201,  6.41633202],
       [ 4.67878373,  5.53345395,  7.68198277,  7.72535819],
       [ 4.65841067,  6.60109269,  8.09470206,  8.64501527],
       [ 4.46697795,  6.75575038,  7.80204639, 10.24693453],
       [ 4.22804705,  6.69591167,  7.26754006,  9.97612183],
       [ 3.98234519,  6.44056043,  6.50002766,  7.83139434],
       [ 3.52610805,  5.29566241,  5.50179385,  6.70261889],
       [ 4.60156907,  5.91383064,  9.46759515,  9.46759519],
       [ 5.05804969,  6.31187698,  9.49603275, 10.39965754],
       [ 5.14920441,  7.80249818,  9.25972226, 10.14429222],
       [ 5.0684481 ,  8.24122567,  9.31244742, 10.15297665],
       [ 4.90036528,  7.